### ISSUE TITLE
!help command lacks !part description 

### ISSUE THREAD

**Issue by HereComesTheMoon** [HereComesTheMoon/TBotD#6]
When calling !help then it will show a list of commands, along with some information on what the command does and how to use it.

But (potentially due to size limitations) it won't show all of the available commands, such as !part or !snooze. When calling `!help part` it will correctly show the help submenu which shows that these commands do in fact exist. 

To fix this, it seems like the !help menu might have to be revamped. It might be necessary to use discord.py to roll our own help menu, there should be a way of doing that. For now, just figuring out how to also display !part would be helpful.

**Comment by TheSkeward** [comment]
looks like this is now working in the current build

**Comment by HereComesTheMoon** [comment]
Appears to be the case. Difficult to say why, might be:
- Due to reordered Cog loading
- Due to updated dependencies (this happened today)
Can't think of any other explanation. Frankly tempted to just close this one, even though the !help menu is overall still pretty messy, and the command categories, including one 'No Category' category are a bit weird. Might leave it open for a few days, then consider closing it. Who knows, maybe the issue will be back after some more code fiddling.

**Comment by HereComesTheMoon** [comment]
Alright, I discovered something really interesting: When I call `!help` in DMs or in a different Discord server, the bot will *omit* the help description of the `Part` cog. If I call `!help` on TBD then it won't. 

I have a suspicion why this might be the case: !part and !rejoin have `@on_tbd()` checks (these are function decorators) attached to them. These decorators check if a predicate is fulfilled, otherwise the command cannot be executed. This is a standard way to gate permissions.

Maybe the `!help` command aggregates the respective data at runtime, and uses the predicates to check if a certain command can currently be used in the first place, and otherwise doesn't show the help at all. This prevents clutter.  

Okay: One quick experiment later, this in fact appears to be the case. This mystery is solved, and it's not really an issue.
