### ISSUE TITLE
Python version management

### ISSUE THREAD

**Issue by HereComesTheMoon** [HereComesTheMoon/TBotD#8]
We use `venv` and `requirements.txt` to fix our dependencies. 

This works reasonably well, at least until our version of Python updates, and suddenly our dependencies cannot be satisfied anymore, or we suddenly get weird issues. Surely there's a way to fix this problem. 

We could use something like `pyenv` to fix the version of Python which we use, for example. We use `match` statements, so we need at least Python 3.10. It'd also be possible to look into just setting up a Docker container (or something along the lines) which takes care of this problem, and could be the default way of deploying and running the bot.

**Comment by TheSkeward** [comment]
Going by the existence of the Dockerfile, it looks like this issue can be closed - the `From python:3.11` directive in your Dockerfile will make sure that Docker will always use that version of Python when building the Docker image.

**Comment by TheSkeward** [comment]
It is worth noting that if you want a certain port to be available to the world outside the container you might want something like `EXPOSE 80` (or whatever port) in the Dockerfile, before running main.py. This just informs Docker that the container listens on the specified network ports at runtime; it doesn't actually publish the port. It's more of a documentation between the person who builds the image and the person who runs the container.
